[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
runner = "elf2uf2-rs -d"  # optional, to flash directly to Pico
rustflags = [
  "-C", "link-arg=-Tmemory.x",
]

[unstable]
build-std = ["core"]
