# .cargo/config.toml

[unstable-features]
build-std = true

[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP2350A"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  # Use this precise format for command line arguments:
  "-C", "link-arg=-nodefaultlibs", 
]
